import Title from "./../../components/title/Title";
import AboutPage from "./../../components/about-page/AboutPage";

import styles from "./../../components/project-block/project-block.module.css";

export default function About() {
  return (
    <>
      {/* <Head>
        <title>Fcore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={styles.block}>
        <Title firstText="О нас." bgText="Роудмап." grayText="Контакты" />
        <AboutPage />
      </div>
    </>
  );
}