"use client"


import Title from "./../../components/title/Title";
import BriefPage from "./../../components/brief/BriefPage";

import styles from "./../../components/project-block/project-block.module.css";
import Footer from "@/components/footer/Footer";

export default function Brief() {
  return (
    <>
      {/* <Head>
        <title>Fcore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={styles.block}>
        <Title firstText="Оставьте свою" bgText="заявку." grayText="Заполните бриф" />
        <BriefPage />
        <Footer />
      </div>
    </>
  );
}